# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\onePiece.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.yolo_translate_tab = QtWidgets.QWidget()
        self.yolo_translate_tab.setObjectName("yolo_translate_tab")
        self.floderPlainTextEdit = QtWidgets.QPlainTextEdit(self.yolo_translate_tab)
        self.floderPlainTextEdit.setGeometry(QtCore.QRect(0, 10, 671, 31))
        self.floderPlainTextEdit.setObjectName("floderPlainTextEdit")
        self.choseFloderPushButton = QtWidgets.QPushButton(self.yolo_translate_tab)
        self.choseFloderPushButton.setGeometry(QtCore.QRect(680, 10, 91, 31))
        self.choseFloderPushButton.setObjectName("choseFloderPushButton")
        self.tabWidget.addTab(self.yolo_translate_tab, "")
        self.yolo_test_tab = QtWidgets.QWidget()
        self.yolo_test_tab.setObjectName("yolo_test_tab")
        self.tabWidget.addTab(self.yolo_test_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choseFloderPushButton.setText(_translate("MainWindow", "选择文件夹"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.yolo_translate_tab), _translate("MainWindow", "yolo转换"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.yolo_test_tab), _translate("MainWindow", "yolo测试"))
        self.menu.setTitle(_translate("MainWindow", "开始"))
